---
- name: Deploy Application on Kubernetes
  hosts: all  # Replace with your target host group
  become: yes  # Run as root
  tasks:

    - name: Copy Kubernetes Deployment YAML to Master Node
      copy:
        src: ./deployment.yml  # Ensure this file is in the same directory as playbook
        dest: /home/admin/deployment.yml
        mode: '0644'

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /home/admin/deployment.yml
      register: kubectl_output
   -  name: create new service
      command: kubectl apply -f /home/admin/Service.yml

    - name: Show Deployment Output
      debug:
        msg: "{{ kubectl_output.stdout }}"
